### ISSUE TITLE
Pdf is not correctly rendered at the first build

### ISSUE THREAD

**Issue by asc84** [PandaScience/FortySecondsCV#12]
I'm on Windows 10 and I use:
XeTeX 3.14159265-2.6-0.999991 (TeX Live 2019/W32TeX)
kpathsea version 6.3.1

When I do the first:
$ xelatex template.tex
Then the PDF is not correctly rendered, there is a small grey box at the top of both pages, but the left sidebar is not grey.
When I run that command again one or max. two times, then it gets fixed.

Please find attached the log from such a bad run and a the generated wrong pdf file.
[template.log](https://github.com/PandaScience/FortySecondsCV/files/3894114/template.log)
[template.pdf](https://github.com/PandaScience/FortySecondsCV/files/3894115/template.pdf)

Otherwise I like your template and I would like to use it, but it would be to be able to build it properly.

Additional info: I found latexmk and if I build with it, then if fixes the issue.
So maybe this is only a documentation issue of README.md, to tell the user to build with:
$ latexmk -pdf -xelatex template.tex
or its lualatex equivalent.

**Comment by PandaScience** [comment]
Hi. Thank you for submitting this bug incl. the log. It should be the same issue as in #5 . I will try to investigate this during my next long train journey.

Anyways, I will add the latexmk line to the readme since that's what I also use in my setup and it seems to work on recent Windows, too. (In fact, I didn't even realize, that there is latexmk for Windows :wink:)

**Comment by PandaScience** [comment]
I finally had some spare time to investigate this bug. 
The misplaced sidebar originates in a [shortcoming (nested TikZ pictures)](https://tex.stackexchange.com/q/283002) in the `background` package I use to place the sidebar. Funny enough, this package was actually used to workaround another already known [TikZ bug](https://tex.stackexchange.com/a/435790). However, I replaced `background` with the `eso-pic` package in commit b3b6edd43c. The template should now compile as expected on first run with all compilers (pdflatex, xelatex and lualatex).

Closes #5.
