### ISSUE TITLE
Underfull \hbox (badness 10000) in paragraph at lines x--y

### ISSUE THREAD

**Issue by renedlog** [PandaScience/FortySecondsCV#13]
There seems an issue in the class file causing tons of \hbox warnings:

`Underfull \hbox (badness 10000) in paragraph at lines 200--210`

**Comment by PandaScience** [comment]
Well, to be honest, I usually ignore such warnings if the visual output looks like expected :wink: , but I can have a look at that issue on the next train journey.
Anyways, thanks for submitting!
