### ISSUE TITLE
Adding additional FontAwesome icons

### ISSUE THREAD

**Issue by sinciciotrofoblast** [PandaScience/FortySecondsCV#14]
Hello! 

This may probably be a very noob question, but would really appreciate your answer: is there any way to add new FontAwesome (FA) icons to be used in the template? It seems I am only able to use the pre-existing ones (18 all together) while it would really great to be able to add new ones from the FA database. 

I read entire readme and couldn't find any explanation and also those icons don't seem to exist in any pics directory? 

Thank you in advance!

**Comment by sinciciotrofoblast** [comment]
Ok, found the answer: http://mirrors.ctan.org/fonts/fontawesome/doc/fontawesome.pdf :)

**Comment by PandaScience** [comment]
Sorry for the late reply, have been on vacation. 
Great you found the answer yourself!
