### ISSUE TITLE
Not all font awesome issues are added

### ISSUE THREAD

**Issue by MieskeB** [PandaScience/FortySecondsCV#17]
Some Font Awesome icons aren't added. I used this list as a reference for the fa5 icons.

http://ftp.snt.utwente.nl/pub/software/tex/fonts/fontawesome5/doc/fontawesome5.pdf

**Comment by PandaScience** [comment]
I just tested a few and so far all of them work on my system. Note, that you only have access to the free icons. Can you give me a specific example?

**Comment by MieskeB** [comment]
Hey, thank you for the response. It's an error on my side... I ran it on a different device and all the icons are working now. 

I absolutely love your template! Thank you very much for letting me use this!

**Comment by PandaScience** [comment]
Great! One issue less :wink:
