### ISSUE TITLE
Date and title are not on the same level in cvitem

### ISSUE THREAD

**Issue by holsair** [PandaScience/FortySecondsCV#20]
Hey.
When creating a \cvitem the date is sometimes not on the same level as the rest of the title line.
The rest of the title line is a little bit lower. In your example it is possible to recognize it quite good at the last entrance of working experience "Bamboo Broker". 
Is it possible to bring this on the same height?

Thank you!

**Comment by PandaScience** [comment]
Hi,
thank you very much for pointing this out. That's a quite serious bug and right now I don't know how to fix that in general. What I can certainly do is aligning everything in the first line, but only on the sacrifice of multi-line bold titles. Give me a few days to find some time to rethink this issue.

**Comment by holsair** [comment]
Hi,
I took a look at the .cls-File of the TwentySecondsCV Template and tried to replace the \cvitem command through their \twentyitem command with some minor modifications.
Now it looks like following:
`
\newcommand{\twentyitem}[4]{%
   \parbox[t]{0.17\textwidth}{\raggedright #1}&
   \parbox[t]{0.81\textwidth}{\textbf{#2}
    \hfill
    {\footnotesize#3}\\%
    #4\vspace{\parsep}%
  }\\}

`

So far it seems that the problem is solved. 
But since I'm a quite new "pure" Latex user (used only LyX so far), I don't now if there are any drawbacks etc. So far the solution works for me. Maybe it was a coincidence and the problem will appear again at some further entries. I willl let you know.

**Comment by PandaScience** [comment]
Ok...I should have had a closer look at the code... there was just a parameter missing.
