### ISSUE TITLE
Need help: Rearrange position of Name, Logo and making cvjobtitle optional

### ISSUE THREAD

**Issue by abmjunaed** [PandaScience/FortySecondsCV#22]
Hi,
I really liked the CV.
But I need some help.

I would like to Put my name between my picture and Logo and also want to make the jobtitle optional.
Could you please help?

Thanks

**Comment by PandaScience** [comment]
Hi @abmjunaed,
you can achieve this by redefining the sidebar like so:
```latex
\renewcommand{\makefrontsidebar}{%
  \begin{sidebar}
    % (most) sidebar commands end with \par; increase space between them
    \setlength{\parskip}{1ex}
    % optionally insert logo picture before profile
    % \plotlogobefore
    \plotprofilepicture
    \plotlogoafter
    {\Huge\color{maincolor}\cvname}
    \par
    % <additional sidebar content>
  \end{sidebar}
}
```
The content is then entirely up to you. In particular, \cvname and \cvjobtitle are not mandatory anymore.
