### ISSUE TITLE
[Tech Query] Related to \begin{cvtable}

### ISSUE THREAD

**Issue by shreyas29** [PandaScience/FortySecondsCV#24]
Could you please explain the difference among below three commands?
-  \begin{cvtable}
- \begin{cvtable}[1.5]
- \begin{cvtable}[3]

**Comment by PandaScience** [comment]
Sure. You can actually find the explanation in the readme under the "[Body](https://github.com/PandaScience/FortySecondsCV#body)" section. I quote from there:

> ```latex
> \begin{cvtable}[<arraystretch>=1]
>   \cvitem{<dates>}{<title>}{<location>}{<description>}
>   \cvitem{<dates>}{<title>}{<location>}{}
>   \cvitemshort{<key>}{<description>}
>   \cvpubitem{<title>}{<author>}{<journal>}{<year>}
> \end{cvtable}
> ```
> - ....
> - `<arraystretch>` modifies the spacing between items of cvtable. For tables of cvitem, you should use at least 1.5, for cvitemshort and cvitem without description, the default value is sufficient.

So in your example, 1.5 and 3 is simply a multiplier for the  space between two consecutive items of the table environment. Leaving out this optional argument is equal to using a multiplier of 1.

**Comment by shreyas29** [comment]
Thanks @PandaScience  :)
