### ISSUE TITLE
[Enhancement] Customization for sidetextcolor

### ISSUE THREAD

**Issue by shreyas29** [PandaScience/FortySecondsCV#25]
I have observed that we can change color of sidebar using \sidecolor.
It would be good if the \sidetextcolor customization can be added so that user would be able to change the text color of sidebar.

**Comment by PandaScience** [comment]
Ok, not much of a change. I added the feature in 337cf1ac8c5a518e0e08d2d7609239d6dbec188a. You can now set the text color for sidebar elements with the new class option `sidetextcolor`. For heavier changes, you can also redefine the `\sidetext` macro. These settings do however not affect some of the graphical sidebar elements like the wheel chart. 

Is this what you meant?

**Comment by shreyas29** [comment]
Thank you so much :) Really appreciate it.
