### ISSUE TITLE
How can I change font size?

### ISSUE THREAD

**Issue by mikelyou** [PandaScience/FortySecondsCV#26]
Thanks for the great template! 😄 

I'm having trouble changing the font size, because all of the fonts are smaller than I want. Is there a variable or a method to change the overhaul font sizes? 

Maybe I'm asking a stupid question, but I've tried for a time and read the documents but cannot find a way to do it. Thanks so much for helping me! 😿

**Comment by PandaScience** [comment]
Since 40sCV is based on the article class, you can use any option that is valid for article here too. In your case, simply add e.g. "12pt" to the list of optional arguments in the `\documentclass` command. This is actually documented in the first line here:
https://github.com/PandaScience/FortySecondsCV#class-options
:wink:

**Comment by mikelyou** [comment]
Thanks for your kindly help! I noticed that afterward, and have tried adding `12pt`, it solved my problem partly, but introduce new problems: some part in the sidebar uses subsubsection's style, and they will be affected not as I wish. What I expect is they change with the content in paragraphs. It's a little hard for me to read this, otherwise I would have designed a new one for myself. Is there a better way to solve this? Thanks again! 😄 

https://github.com/PandaScience/FortySecondsCV/blob/337cf1ac8c5a518e0e08d2d7609239d6dbec188a/fortysecondscv.cls#L266-L272

**Comment by PandaScience** [comment]
I added the class option `sidesectionsize` in 1ec06564931 which allows you to change this manually. I also updated the readme accordingly. Hope that helps.

**Comment by mikelyou** [comment]
Thanks so much! ❤️  It helps a great deal. 😸
