### ISSUE TITLE
How can I increase the width of the year column in Education?

### ISSUE THREAD

**Issue by meatless-tim** [PandaScience/FortySecondsCV#41]
I want to add a specific month to the year part in education section. The current line width will result in two lines after adding the month, which is not very beautiful.
Where can I modify the width of the year column in the .cls file?
Thank you so much.

我想在教育部分添加具体的月份，目前的行宽加入月份后会导致变成两行，不是很美观。
请问在cls文件中，哪里可以修改年份那一列的宽度。
麻烦你了。

**Comment by PandaScience** [comment]
I've quickly made it adjustable via a new class option: `datecolwidth` :wink:
