### ISSUE TITLE
Is there an environment for plain text?

### ISSUE THREAD

**Issue by kuseler** [PandaScience/FortySecondsCV#42]
I added the following for a cover letter:

```

\begin{sidebar}
\begin{sidebarminipage}

		% optionally insert logo picture before profile
		\plotlogobefore

		% optionally insert profile picture
		\plotprofilepicture

		% optionally insert logo picture after profile
		\plotlogoafter

		\vspace{1ex}

		% name and job
		\nameandjob

		% personal information
		\vspace*{0.5em}
		\begin{icontable}[1.6]{1.7em}{0.4em}
			\personaldata
		\end{icontable}

		% user definitions\end{sidebarminipage}
\end{sidebarminipage}
\end{sidebar}

%  \newgeometry{
%  	top=0.5in,
%  	bottom=\topbottommargin,
%  	right=\leftrightmargin,
%  	left=\leftrightmargin
%  }

\cvsection{Lorem Ipsum}

{\LARGE dear ladies and gentlemen, \\

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, \\

consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
}

\newpage
```
to the top of my cv as a cover letter, it isn't properly formatted: 
* The size of the second paragraph seems smaller
* (not with this text) Some words are cut off.
* (not with this text) Some words break through the margin for some reason

![grafik](https://user-images.githubusercontent.com/47039588/202435264-50c5292a-c060-4334-aa8a-dba3ef367dff.png)

Is there a fix or some advice on how to resolve these issues?

**Comment by PandaScience** [comment]
Hi and sorry for the late reply.

Well, this class was never meant to be used for cover letters, especially since the sidebar is a quite uncommon thing there. Personally, I prefer the clean style of the [moderncv class]( https://ctan.org/pkg/moderncv?lang=en) for that purpose. 

If you really want to enforce it, you could put your prose text in sth like a parbox:

```
\parbox{\linewidth}{
  \LARGE
  dear ladies and gentlemen, \\
  Lorem ipsum dolor sit amet... \\
  consetetur sadipscing elitr, ...sit amet.
}
```

**Comment by kuseler** [comment]
I thought it would be nice to have the cover letter be coherent with the rest of the template.
