### ISSUE TITLE
No flags for most languages

### ISSUE THREAD

**Issue by DavidSiretMarques** [PandaScience/FortySecondsCV#43]
I'm using this template to create my CV and I've found no flags for most languages/countries, and no way of adding them myself. the link in the flags folder redirects to an enterprise page that doesn't seem to be the one from which the images were drawn.

**Comment by PandaScience** [comment]
The flag icons are simple PNGs and the `\flag` command is merely a wrapper around `\includegraphics` with some additional options, so you are free to use whatever image source you like for flags. Regarding the correct link, you can find it in the template's source code: https://github.com/PandaScience/FortySecondsCV/blob/main/template.tex#L146 

The bundled copies in the `flags` folder were never meant to be "complete", but rather just enough to compile the provided example CV. However, I don't see any harm in providing the full set as git submodule. From a license POV it's actually even better. :wink: :+1: 

So yeah, you have now access to the entire [gosquared flags repo](https://github.com/gosquared/flags) after initializing the submodule:
```
git submodule init   # or
git submodule update --init
```
