### ISSUE TITLE
How to wrap a super long University name?

### ISSUE THREAD

**Issue by Firestar99** [PandaScience/FortySecondsCV#47]
![image](https://github.com/PandaScience/FortySecondsCV/assets/31222740/e5101a2e-f195-4b50-a499-5ee349c6b753)

Would appreciate any ideas on how to insert a line break into the Uni's name. Using either `\\` or `\newline` in the Uni's name creates this:

![image](https://github.com/PandaScience/FortySecondsCV/assets/31222740/ef65bc69-f9df-41e2-a116-78dcc36241d9)

Thanks for any help :D
Worst case I will just keep it blank and write it in cursive or something in the first line of the description.

```latex
\cvsection{Education}
\begin{cvtable}[1.5]
	\cvitem{2045 onwards}{Master in some IT subject with a long name}{University of applied Sciences Somecity}
		{German \enquote{Hochschule Somecity} translates to \enquote{University of applied Sciences Somecity} which is super long and breaks this layout}
\end{cvtable}
```

**Comment by PandaScience** [comment]
Congratulations, you found one of the weak spots in this CV class :wink: 

To best of my knowledge, I cannot make this dynamically adjustable for all cases. I think the best you can do is passing a parbox of a certain fixed width instead of plain text as location argument like so:

```latex
\cvsection{Education}
\begin{cvtable}[1.5]
	\cvitem{2045 onwards}{Master in some IT subject with a long name}{%
		\parbox[t]{<FIXED_LENGTH>}{%
			University of applied Sciences Somecity
		}%
		{German \enquote{Hochschule Somecity} translates to \enquote{University of applied Sciences Somecity} which is super long and breaks this layout}
\end{cvtable}
```
with `<FIXED_LENGTH>` set to something like `10em`.

**Comment by Firestar99** [comment]
Thanks, works perfectly!
