### ISSUE TITLE
Package graphics Error: Division by 0. \makefrontsidebar while compiling template.tex

### ISSUE THREAD

**Issue by leland45** [PandaScience/FortySecondsCV#5]
I just downloaded and install your class file, but I'm unable to get the \makefrontsidebar works properly with your exemple code template.tex. I get the joined .pdf file as a result. Could you provide some help?
[template.pdf](https://github.com/PandaScience/FortySecondsCV/files/3693282/template.pdf)

**Comment by PandaScience** [comment]
Hi there, sorry for the late reply. I will look into this issue soon.

**Comment by ifokkema** [comment]
@leland45: I get this too, but if I recompile, the problem goes away. I haven't looked into it any further, though.

**Comment by ifokkema** [comment]
Small correction; I don't get this "Package graphics Error", but I do see the sidebar background off like that. Recompiling fixes that problem for me.
