### ISSUE TITLE
Would it be possible to implement itemize for cvitem

### ISSUE THREAD

**Issue by philodavies** [PandaScience/FortySecondsCV#9]
I'd like to have a list of items allowed under cvitem such as:

```
 date part1     Description                                                    location
 date part2     - description 1
                - description ..
                - description N
```

Do you think this might be possible? I'm looking to see if I can find the solution myself, but I'm wondering if this might be useful to other people as well

**Comment by PandaScience** [comment]
Well, nothing stops you from inserting an itemize environment into any of the fields of `\cvitem`. Looking at your example I guess you neither want indentation nor item separation, so I suggest you use the `enumitem` package like so:

```latex
% put this in preamble
\usepackage{enumitem}
.
.
.
% put this in main part
\begin{cvtable}
  \cvitem{date part1}{Description}{location}{}
  \cvitemshort{date part2}{
    possibly another header here
    \begin{itemize}[leftmargin=*, noitemsep, topsep=0pt]
      \item description 1
      \item description ..
      \item description N
    \end{itemize}
  }
\end{cvtable}
```

**Comment by philodavies** [comment]
Thanks for the quick reply!

This is a step in the right direction, but for some reason there is additional whitespace when the list gets added to cvitem.

This is the code I used: 
```
\cvsection{Test 2}
\begin{cvtable}
  \cvitem{Jan 2019 -- Dec 2019}{Description}{location}{
    \begin{itemize}[leftmargin=*, noitemsep, topsep=0pt]
      \item description 1
      \item description ..
      \item description N\\
    \end{itemize}
  }
  \cvitem{Jan 2018 -- Dec 2018}{Description}{location}{Description normal}
\end{cvtable}
```
Output:
![resume_list_example](https://user-images.githubusercontent.com/40214783/68087906-dcb27600-fe51-11e9-9c2a-941f3ad4cd6c.PNG)

**Comment by philodavies** [comment]
At first my idea was to implement a new `cvitem` called `cvitemlist` which would contain 4 arguments or more and create the list within the \newcommand definition of the command

**Comment by PandaScience** [comment]
No need for that. Just use `\cvitemshort` as I did in the example code above. You can freely mix `\cvitem` and `\cvitemshort` in a `cvtable` environment.

**Comment by philodavies** [comment]
Thanks for your help!

The solution for removing the extra linebreak is the following:
`\vspace{-4mm}`

Gives: 
```
\cvsection{Test 2}
\begin{cvtable}
  \cvitem{Jan 2019 -- Dec 2019}{Description}{location}{
    \vspace{-4mm}
    \begin{itemize}[leftmargin=*, noitemsep, topsep=0pt]
      \item description 1
      \item description ..
      \item description N\\
    \end{itemize}
  }
  \cvitem{Jan 2018 -- Dec 2018}{Description}{location}{Description normal}
\end{cvtable}
```

Output:
![resume_list](https://user-images.githubusercontent.com/40214783/68088264-26e92680-fe55-11e9-8cee-3476d2ccfd53.PNG)
